securityContexts: {}

workers:
  securityContexts: {}

redis:
  enabled: false
  
postgresql:
  enabled: false

data:
  metadataConnection:
    host: airflow-psql
    user: postgres
    pass: airflow
