redis:
  enabled: false
  
postgresql:
  enabled: false

rbac:
  create: true
  createSCCRoleBinding: true

data:
  brokerUrl: redis://:airflow@airflow-redis
  metadataConnection:
    host: airflow-psql
    user: postgres
    pass: airflow

dags:
  gitSync:
    enabled: true
    repo: https://github.com/fjcloud/airflow-dags.git
    branch: main
